name: Atualizar README Automaticamente

on:
  schedule:
    # Executa diariamente às 6h da manhã
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Permite execução manual
  push:
    # Executa quando há mudanças nos arquivos principais
    paths:
      - 'app.py'
      - 'tests/**'
      - 'templates/**'
      - 'requirements.txt'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Executar script de atualização
      run: |
        python update_readme.py
        
    - name: Verificar mudanças
      id: check_changes
      run: |
        if git diff --quiet README.md; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit e push das mudanças
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "docs: atualização automática do README [skip ci]"
        git push
        
    - name: Notificar sucesso
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        echo "✅ README atualizado com sucesso!"
        
    - name: Notificar sem mudanças
      if: steps.check_changes.outputs.changes == 'false'
      run: |
        echo "ℹ️ README já está atualizado" 